project_identifier_env: CROWDIN_PROJECT_ID
api_key_env: CROWDIN_API_KEY
base_path: "./"
preserve_hierarchy: true

files:
  -
    source: 'source/**/*.md'
    translation: 'source/%locale%/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'pt-BR': 'pt-BR'
